# Generated by Django 4.1.13 on 2023-12-29 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 10, 54, 0, 27515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(default=datetime.datetime(2023, 12, 29, 10, 54, 0, 27432, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
        ),
    ]
