# Generated by Django 4.1.13 on 2023-12-17 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_rename_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ManyToManyField(related_name='wallet_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
