# Generated by Django 4.1.13 on 2023-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_subcategory_spending_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
