# Generated by Django 4.1.13 on 2023-11-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_spending_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
