# Generated by Django 4.1.13 on 2023-12-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='users',
        ),
    ]
