# Generated by Django 4.1.13 on 2023-11-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_income_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique_for_date='created_at'),
        ),
    ]
