# Generated by Django 4.1.13 on 2023-12-19 13:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0005_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 13, 9, 38, 801332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(default=datetime.datetime(2023, 12, 19, 13, 9, 38, 801231, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
        ),
    ]
