# Generated by Django 4.1.13 on 2023-12-19 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_invite_is_deleted_invite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 13, 10, 44, 29894, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(default=datetime.datetime(2023, 12, 19, 13, 10, 44, 29747, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
        ),
    ]
