# Generated by Django 4.1.13 on 2023-11-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_income_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('spending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_comment', to='wallet.spending')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='IncomeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_comment', to='wallet.income')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='spendingcomment',
            index=models.Index(fields=['created'], name='wallet_spen_created_d5fb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecomment',
            index=models.Index(fields=['created'], name='wallet_inco_created_4f1ea5_idx'),
        ),
    ]
