# Generated by Django 4.1.13 on 2023-12-19 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_invite_expiration_date_alter_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 13, 49, 51, 120444, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(default=datetime.datetime(2023, 12, 19, 13, 49, 51, 120339, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
        ),
    ]
