# Generated by Django 4.1.13 on 2023-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_income_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spending',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
