# Generated by Django 4.1.13 on 2023-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_income_comment_spending_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spending',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
